spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/football
    username: root
    password: dnana123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update